In [1]:
import numpy as np

# Массив из списка Python
arr_from_list = np.array([1, 2, 3, 4, 5])
print("Массив из списка:", arr_from_list)

Массив из списка: [1 2 3 4 5]


In [2]:
# Двумерный массив из вложенного списка
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("Двумерный массив:\n", matrix)

Двумерный массив:
 [[1 2 3]
 [4 5 6]]


In [3]:
# Массив нулей (размером 3x2)
zeros_arr = np.zeros((3, 2))
print("Массив нулей:\n", zeros_arr)

Массив нулей:
 [[0. 0.]
 [0. 0.]
 [0. 0.]]


In [4]:
# Массив единиц (длина 4)
ones_arr = np.ones(4)
print("Массив единиц:", ones_arr)

Массив единиц: [1. 1. 1. 1.]


In [5]:
# Массив с диапазоном значений (от 0 до 10 с шагом 2)
range_arr = np.arange(0, 10, 2)
print("Массив с диапазоном:", range_arr)

Массив с диапазоном: [0 2 4 6 8]


In [6]:
print("\nАтрибуты matrix:")
print("Форма (shape):", matrix.shape)  # Размерность массива
print("Тип данных (dtype):", matrix.dtype)  # Тип элементов


Атрибуты matrix:
Форма (shape): (2, 3)
Тип данных (dtype): int64


In [7]:
# Одномерный массив для примеров
sample_arr = np.array([10, 20, 30, 40, 50])
# Получение элемента по индексу
print("\nЭлемент с индексом 2:", sample_arr[2])

# Срез от элемента 1 до 3 (включительно)
print("Срез [1:4]:", sample_arr[1:4])

# Многомерный пример (первая строка, второй столбец)
print("Элемент matrix[0, 1]:", matrix[0, 1])


Элемент с индексом 2: 30
Срез [1:4]: [20 30 40]
Элемент matrix[0, 1]: 2


In [8]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Поэлементное сложение
elementwise_sum = a + b
print("\nПоэлементная сумма:", elementwise_sum)

# Поэлементное умножение
elementwise_mul = a * b
print("Поэлементное произведение:", elementwise_mul)

# Статистические функции
print("Среднее значение a:", np.mean(a))
print("Максимум в b:", np.max(b))
print("Стандартное отклонение a:", np.std(a))


Поэлементная сумма: [5 7 9]
Поэлементное произведение: [ 4 10 18]
Среднее значение a: 2.0
Максимум в b: 6
Стандартное отклонение a: 0.816496580927726
